;customize ffip
(setq ffip-patterns (list "*.html"
                          "*.org"
                          "*.txt"
                          "*.md"
                          "*.el"
                          "*.clj"
                          "*.py"
                          "*.rb"
                          "*.js"
                          "*.pl"
                          "*.sh"
                          "*.erl"
                          "*.hs"
                          "*.ml"
                          "Gemfile"
                          "*.yml"
                          "*.gemspec"
                          "*.json"))
